version: "3.7"
services:
  nginx:
    image: nginx:latest
    volumes:
    - type: bind
      source: ./nginx.conf
      target: /etc/nginx/nginx.conf
    ports:
      - target: 80
        published: 80
        protocol: tcp
    depends_on:
      - service1
      - service2
      - service3
      - service4
  service1:
    image: jenkins-cookie:5000/service1
    build:
      context: ./service1
    environment:
      - MY_SQL_USER=${MY_SQL_USER}
      - MY_SQL_PASSWORD=${MY_SQL_PASSWORD}
      - MY_SQL_DB=${MY_SQL_DB}
      - MY_SQL_URL=${MY_SQL_URL}
      - SECRET_KEY=${SECRET_KEY}
  service2:
    image: jenkins-cookie:5000/service2
    build:
      context: ./service2
    environment:
      - MY_SQL_USER=${MY_SQL_USER}
      - MY_SQL_PASSWORD=${MY_SQL_PASSWORD}
      - MY_SQL_DB=${MY_SQL_DB}
      - MY_SQL_URL=${MY_SQL_URL}
      - SECRET_KEY=${SECRET_KEY}

  service3:
    image: jenkins-cookie:5000/service3
    build:
      context: ./service3
    environment:
      - MY_SQL_USER=${MY_SQL_USER}
      - MY_SQL_PASSWORD=${MY_SQL_PASSWORD}
      - MY_SQL_DB=${MY_SQL_DB}
      - MY_SQL_URL=${MY_SQL_URL}
      - SECRET_KEY=${SECRET_KEY}

  service4:
    image: jenkins-cookie:5000/service4
    build:
      context: ./service4
      dockerfile: Dockerfile
    environment:
      - MY_SQL_USER=${MY_SQL_USER}
      - MY_SQL_PASSWORD=${MY_SQL_PASSWORD}
      - MY_SQL_DB=${MY_SQL_DB}
      - MY_SQL_URL=${MY_SQL_URL}
      - SECRET_KEY=${SECRET_KEY}
