- hosts: swarmonly
  become_user: jenkins
  tasks:
  - name: "git clone repo"
    git:
      repo: https://github.com/Miss-Rhyme/Project2.git
      dest: ~/Project2
      version: feature1
  - name: "docker compose up in swarm master"
    docker_compose:
      project_src: ~/Project2
      build: yes
    register: output
  - name: "docker compose down"
    docker_compose:
      project_src: ~/Project2
      state: absent
  - name: "push service1 image to registry"
    command: "docker-compose push"
 - name: "deploy stack"
    docker_stack:
      name: stack
      state: present
      compose: ~/Project2/docker-compose.yaml
  - name: "replicate"
    command: docker service update --replicas 7
